abi3audit/_object.py

This is both more correct and should offer a nice performance boost.
Closes #13.
Signed-off-by: William Woodruff <william@trailofbits.com>

_object: filter non-external symbols in dylibs

---

.github/workflows/ci.yml

Signed-off-by: William Woodruff <william@trailofbits.com>

workflows/ci: add Python 3.11 to test matrix

---

abi3audit/_audit.py

This is a first workaround to exclude certain CPython symbols that are not listed as part of the limited API / ABI3-compatible, but in practice always compile to ABI3 code.
Part 1) of #85.

Add Py_XDECREF to new allowed symbol list

---

Makefile

The option for VENV_EXISTS was hardcoded, which might have been an oversight given that the ability to override the venv is mentioned at the top of the file.

fix: Create venv in configured directory

---

abi3audit/_audit.py
abi3audit/_object.py
test/test_audit.py

This is the final step in selective auditing: Obtaining the symbol visibility info, and then deciding if this symbol is an ABI3 violation with the found visibility.
The rationale is that the non-ABI3-tagged symbols which we know can be legal are all static inline, which means they should show up as local in a symbol table.
-----------------
Currently only Linux - I took the map values from [this SO thread](https://stackoverflow.com/questions/48181509/how-to-interpret-the-st-info-field-of-elf-symbol-table-section) quoting `man elf`.
Mach-O is harder. It gives me a bunch of binary values as ints, and I'm not sure how to interpret them. The returned type for `symbol` is `NList64`, which is a Python version of this struct: https://llvm.org/doxygen/structllvm_1_1MachO_1_1nlist__64.html …

Get visibilities from shared objects to use them in filtering

---

abi3audit/_object.py

This _should_ fix #94.
CC @nicholasjng as well, since this was your feature 😉

_object: skip unknown ELF visibilities

---

README.md
abi3audit/_cli.py

Changes to make abi3audit behave more like all compiler tools and be quiet by default. The summary is now only output if there are violations or ABI version mismatches. The only noise seen now when using abi3audit in a build system is when there is something one should look at. The new optional --summary argument will output the summary even if the reported violations/ABI version mismatches are zero.

Add --summary and be more quiet by default

---

abi3audit/_object.py

This is a non-actionable warning that's primarily useful for debugging, so recategorize it.
Closes #101.

_object: lower warning to debug

---

.github/workflows/release.yml

Moves OIDC and other permissions out of the build step, which needs nothing.
Closes #104.

workflows/release: refactor into separate steps

---

README.md
abi3audit/_audit.py
pyproject.toml

Updates various slugs to the PyPA repo URL.

update project URLs

---

abi3audit/_audit.py

See discussion in #111.
CC @giampaolo

_audit: relax PyInit check

---

abi3audit/_cli.py
abi3audit/_extract.py
test/test_extract.py

This PR is mostly done to fix #117, but also improves another error message which I noticed while making it.
Unfortunately I don't know how to add tests for the CLI behaviour and there doesn't seem to be any existing ones, so I've only tested this manually but at least it does seem to work as expected:
```console
$ python -m abi3audit foo.so
[17:50:51] 👎 processing error: 'foo.so' must contain '.abi3.' to be recognized as a shared object
```

Improve error message when `.so` file without `.abi3.` in it is specified

---

abi3audit/_audit.py
abi3audit/_cli.py
abi3audit/_extract.py
abi3audit/_object.py
test/test_extract.py

Allow auditing arbitrary shared objects, not necessarily containing ".abi3." in their name, if --assume-minimum-abi3 option is specified: suppose that all shared objects use this ABI3 version then.
This makes the tool more convenient to use for non-wheel-packaged extensions.
Also specify the default, 3.2, ABI version in a single place only and use "None" instead of the default value elsewhere.
----
Sorry, I couldn't prevent myself from making this PR, implementing the suggestion discussed in #117. This may address #116 too, but mostly it makes the tool much more convenient for me to use, as I don't have to rename all the files (or create symlinks for them) before running it on them.

Use assumed ABI3 version for shared objects without ".abi3."

---

abi3audit/_cli.py

Current output for new option in a commonly used output format of program name followed by version number:
```
$ python -m abi3audit --version
abi3audit 0.0.19
```

Add --version option to show abi3audit version information

---

abi3audit/_cli.py

This is more in line with user expectations, and results in tables being rendered when invoking `abi3audit <spec> -v`, even without `--summary`.
`--summary` behavior itself is unchanged, as is the rendering algorithm.
---------------------
On the other feature branch, testing on Dockerfile v3.3.1, CPython 3.8, manylinux, this results in:
```
$ abi3audit wheelhouse/dockerfile-3.3.1-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.whl -v   
[19:55:27] 👎 dockerfile-3.3.1-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.whl: dockerfile.abi3.so has non-ABI3 symbols                                                    
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┓                                                                                                                       
┃ Symbol …
```

Make `--verbose` imply `--summary` on the command line

---

abi3audit/_audit.py

Previously, when violations were found (i.e. non-ABI3 symbols in an ABI3-tagged extension), any subsequent version mismatches (i.e. using symbols that were made part of the stable ABI, but in later versions than the provided wheel was built for), were left unreported.
This is now fixed, by changing the audit rendering hook to include all offending symbols and their ABI versions. In case of a violation, the "not ABI3" value is given as ABI version, to clearly signal that the found symbol is not part of any version of the stable ABI.
-------------------
Hey! I saw the open issue and took a stab, since I also ran into this in a C++ bindings project build. 
No new code, just some reorg - the changes in observable behavior are the rendering of both "thumbs down" messages in the case of …

cli: Render both mismatches and violations in the same table

---

abi3audit/_extract.py

Packaging specifiers are implemented as described in https://packaging.python.org/en/latest/specifications/version-specifiers/, although I did not find a specific PEP for them. Everything is done using `packaging`'s own APIs, so there are no egregious hacks brought into the spec parsing logic.
This allows to audit version-specific packages, which makes it easier to pin down regressions in ABI3 compatibility.
Usage: `abi3audit cryptography==42.0.7 -v`.
Currently lacks support for version ranges, but that is only a regex tweak away thanks to the terrific `SpecifierSet` API.
------------------
Hello again, I'm on a roll! I was surprised to see that version-specific auditing of a PyPI package was not supported, so I quickly added it. On this branch (please try it out as well), I get:
```
$ …
```

Allow packaging specifiers in packages when auditing on PyPI

---

abi3audit/_extract.py
test/test_extract.py

Requirements are processed as dictated by `packaging.requirements.Requirement`.
In essence, this also allows auditing a pinned requirements.txt file as generated e.g. by `uv pip compile`.
Caveat: Only PyPI URLs are audited, no custom indexes / git dependencies are supported.
----------------------------
A CLI test on this branch:
```
$ abi3audit -v "google-benchmark>=1.8.0,<2"
[10:41:20] 💁 google-benchmark>=1.8.0,<2: 5 extensions scanned; 0 ABI version mismatches and 0 ABI violations found 
```
Requirement errors are given as hints to the processing error:
```
$ abi3audit -v "google-benchm?rk>=1.8.0,<2"
[10:42:51] 👎 processing error: 'google-benchm?rk>=1.8.0,<2' does not look like a valid wheel, shared object, or package name                                                   
hint: …
```

Allow general requirements as PyPISpec inputs

---

abi3audit/_audit.py

Not technically part of the stable ABI until
3.14, but is defined as `static inline` when
used with the limited API and therefore
exhibits the same indirect ABI compatibility
behavior as `Py_XDECREF`.
~~NB: I haven't done anything with `Py_NewRef`/`_Py_NewRef`
yet, pending clarification on #137.~~
Closes #137.

audit: add Py_TYPE to allowed symbols list

---

abi3audit/_audit.py
abi3audit/_cli.py
abi3audit/_extract.py
abi3audit/_object.py

B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling

Apply ruff/flake8-bugbear rule B904

---

abi3audit/_audit.py
abi3audit/_cli.py
abi3audit/_extract.py
abi3audit/_object.py
pyproject.toml
uv.lock

This is why I assume the ABI version could be `None`:
https://github.com/pypa/abi3audit/blob/ca87d3a059bbdde7d97904996ba60a36529d27e5/abi3audit/_object.py#L62-L63

Enforce more ruff rules
